---
sudo: required
dist: bionic
addons:
  apt:
    packages:
      - python3
      - python3-pip
      - python3-setuptools

env:
  - ANSIBLE_VERSION=2.9.25
  - ANSIBLE_VERSION=2.10.7
  - ANSIBLE_VERSION=3.4.0
  - ANSIBLE_VERSION=4.4.0

services:
  - docker

before_install:
  - sudo pip3 install ansible==${ANSIBLE_VERSION}
  - sudo pip3 install molecule 'molecule[docker]' docker testinfra ansible-lint yamllint
  - git clone https://github.com/ansible/galaxy-lint-rules.git

script:
  - ansible --version
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
