sudo: required
language: ruby

env:
  - ANSIBLE_VERSION=2.4
  - ANSIBLE_VERSION=2.5
  - ANSIBLE_VERSION=2.6
  - ANSIBLE_VERSION=2.7
services:
  - docker

before_install:
  - bundle install

script:
  - kitchen conv certbot-debian-9
  - kitchen conv certbot-debian-9 | grep changed=0
  - kitchen verify certbot-debian-9

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
