---
- name: Converge
  hosts: all
  roles:
    - ansible-role-certbot
  vars:
    certbot_role: slave
    certbot_domains:
      - name: test.local
        command: 'echo OK > /tmp/test.txt'

  pre_tasks:
    - name: update apt cache
      ansible.builtin.apt:
        update_cache: true
